export const ANIMATION_DURATION = 600; // How long each animation plays and player input is disabled, in ms
export const CELL_SIDE = 64; // This is width in pixels for styling. Character sprites should be about this size.
export const GRID_HEIGHT = 20; // Number of cells
export const GRID_WIDTH = 30; // Number of cells
export const MAX_ROOMS = 25;
export const ROOM_SIZE_RANGE = [2, 8]; // [min, max]
export const TOTAL_CELLS = GRID_HEIGHT * GRID_WIDTH;
export const VIEW_HEIGHT = 9;
export const VIEW_WIDTH = 14;
